name: "deeptau_core"
platform: "tensorflow_graphdef"
max_batch_size: 0
input [
  {
    name: "input_tau"
    data_type: TYPE_FP32
    dims: [ -1, 47 ]
  },
  {
    name: "input_inner"
    data_type: TYPE_FP32
    dims: [ -1, 11, 11, 64 ]
  },
  {
    name: "input_outer"
    data_type: TYPE_FP32
    dims: [ -1, 21, 21, 64 ]
  }
]
output [
  {
    name: "main_output/Softmax"
    data_type: TYPE_FP32
    dims: [ -1, 4 ]
  }
]
