name: "facile_all_v2"
platform: "tensorflow_graphdef"
max_batch_size: 160000
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 47 ]
  }
]
output [
  {
    name: "output/BiasAdd"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
dynamic_batching {
  preferred_batch_size: [ 16000 ]
  max_queue_delay_microseconds: 100
}

