name: "deeptau_inner"
platform: "tensorflow_graphdef"
max_batch_size: 0
input [
  {
    name: "input_inner_egamma"
    data_type: TYPE_FP32
    dims: [ -1, 1, 1, 86 ]
  },
  {
    name: "input_inner_muon"
    data_type: TYPE_FP32
    dims: [ -1, 1, 1, 64 ]
  },
  {
    name: "input_inner_hadrons"
    data_type: TYPE_FP32
    dims: [ -1, 1, 1, 38 ]
  }
]
output [
  {
    name: "inner_all_dropout_4/Identity"
    data_type: TYPE_FP32
    dims: [ -1, 1, 1, 64 ]
  }
]
