# deepmet has two versions:
# 1 is for the resolution tune
# 2 is for the response tune

name: "deepmet2"
platform: "tensorflow_graphdef"
max_batch_size: 100
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 4500, 8 ]
  },
  {
    name: "input_cat0"
    data_type: TYPE_FP32
    dims: [ 4500, 1 ]
  },
  {
    name: "input_cat1"
    data_type: TYPE_FP32
    dims: [ 4500, 1 ]
  },
  {
    name: "input_cat2"
    data_type: TYPE_FP32
    dims: [ 4500, 1 ]
  }
]
output [
  {
    name: "output/BiasAdd"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

dynamic_batching {
    #preferred_batch_size: [ 8, 16 ]
    max_queue_delay_microseconds : 100000
}
