name: "facile_all_v5"
platform: "tensorflow_savedmodel"
max_batch_size: 160000
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 46 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]
instance_group [
  {
    kind: KIND_GPU,
    count: 1
  }
]
dynamic_batching {
  preferred_batch_size: [ 16000 ]
  max_queue_delay_microseconds: 100
}

